<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use App\Models\Kota;
use Illuminate\Database\Seeder;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('kotas')->insert([

            ['id' => '1101','id_provinsi' => '11','kode_kota' => '1101','kota' => 'KABUPATEN SIMEULUE'],
            ['id' => '1102','id_provinsi' => '11','kode_kota' => '1102','kota' => 'KABUPATEN ACEH SINGKIL'],
            ['id' => '1103','id_provinsi' => '11','kode_kota' => '1103','kota' => 'KABUPATEN ACEH SELATAN'],
            ['id' => '1104','id_provinsi' => '11','kode_kota' => '1104','kota' => 'KABUPATEN ACEH TENGGARA'],
            ['id' => '1105','id_provinsi' => '11','kode_kota' => '1105','kota' => 'KABUPATEN ACEH TIMUR'],
            ['id' => '1106','id_provinsi' => '11','kode_kota' => '1106','kota' => 'KABUPATEN ACEH TENGAH'],
            ['id' => '1107','id_provinsi' => '11','kode_kota' => '1107','kota' => 'KABUPATEN ACEH BARAT'],
            ['id' => '1108','id_provinsi' => '11','kode_kota' => '1108','kota' => 'KABUPATEN ACEH BESAR'],
            ['id' => '1109','id_provinsi' => '11','kode_kota' => '1109','kota' => 'KABUPATEN PIDIE'],
            ['id' => '1110','id_provinsi' => '11','kode_kota' => '1110','kota' => 'KABUPATEN BIREUEN'],
            ['id' => '1111','id_provinsi' => '11','kode_kota' => '1111','kota' => 'KABUPATEN ACEH UTARA'],
            ['id' => '1112','id_provinsi' => '11','kode_kota' => '1112','kota' => 'KABUPATEN ACEH BARAT DAYA'],
            ['id' => '1113','id_provinsi' => '11','kode_kota' => '1113','kota' => 'KABUPATEN GAYO LUES'],
            ['id' => '1114','id_provinsi' => '11','kode_kota' => '1114','kota' => 'KABUPATEN ACEH TAMIANG'],
            ['id' => '1115','id_provinsi' => '11','kode_kota' => '1115','kota' => 'KABUPATEN NAGAN RAYA'],
            ['id' => '1116','id_provinsi' => '11','kode_kota' => '1116','kota' => 'KABUPATEN ACEH JAYA'],
            ['id' => '1117','id_provinsi' => '11','kode_kota' => '1117','kota' => 'KABUPATEN BENER MERIAH'],
            ['id' => '1118','id_provinsi' => '11','kode_kota' => '1118','kota' => 'KABUPATEN PIDIE JAYA'],
            ['id' => '1171','id_provinsi' => '11','kode_kota' => '1171','kota' => 'KOTA BANDA ACEH'],
            ['id' => '1172','id_provinsi' => '11','kode_kota' => '1172','kota' => 'KOTA SABANG'],
            ['id' => '1173','id_provinsi' => '11','kode_kota' => '1173','kota' => 'KOTA LANGSA'],
            ['id' => '1174','id_provinsi' => '11','kode_kota' => '1174','kota' => 'KOTA LHOKSEUMAWE'],
            ['id' => '1175','id_provinsi' => '11','kode_kota' => '1175','kota' => 'KOTA SUBULUSSALAM'],
            ['id' => '1201','id_provinsi' => '12','kode_kota' => '1201','kota' => 'KABUPATEN NIAS'],
            ['id' => '1202','id_provinsi' => '12','kode_kota' => '1202','kota' => 'KABUPATEN MANDAILING NATAL'],
            ['id' => '1203','id_provinsi' => '12','kode_kota' => '1203','kota' => 'KABUPATEN TAPANULI SELATAN'],
            ['id' => '1204','id_provinsi' => '12','kode_kota' => '1204','kota' => 'KABUPATEN TAPANULI TENGAH'],
            ['id' => '1205','id_provinsi' => '12','kode_kota' => '1205','kota' => 'KABUPATEN TAPANULI UTARA'],
            ['id' => '1206','id_provinsi' => '12','kode_kota' => '1206','kota' => 'KABUPATEN TOBA SAMOSIR'],
            ['id' => '1207','id_provinsi' => '12','kode_kota' => '1207','kota' => 'KABUPATEN LABUHAN BATU'],
            ['id' => '1208','id_provinsi' => '12','kode_kota' => '1208','kota' => 'KABUPATEN ASAHAN'],
            ['id' => '1209','id_provinsi' => '12','kode_kota' => '1209','kota' => 'KABUPATEN SIMALUNGUN'],
            ['id' => '1210','id_provinsi' => '12','kode_kota' => '1210','kota' => 'KABUPATEN DAIRI'],
            ['id' => '1211','id_provinsi' => '12','kode_kota' => '1211','kota' => 'KABUPATEN KARO'],
            ['id' => '1212','id_provinsi' => '12','kode_kota' => '1212','kota' => 'KABUPATEN DELI SERDANG'],
            ['id' => '1213','id_provinsi' => '12','kode_kota' => '1213','kota' => 'KABUPATEN LANGKAT'],
            ['id' => '1214','id_provinsi' => '12','kode_kota' => '1214','kota' => 'KABUPATEN NIAS SELATAN'],
            ['id' => '1215','id_provinsi' => '12','kode_kota' => '1215','kota' => 'KABUPATEN HUMBANG HASUNDUTAN'],
            ['id' => '1216','id_provinsi' => '12','kode_kota' => '1216','kota' => 'KABUPATEN PAKPAK BHARAT'],
            ['id' => '1217','id_provinsi' => '12','kode_kota' => '1217','kota' => 'KABUPATEN SAMOSIR'],
            ['id' => '1218','id_provinsi' => '12','kode_kota' => '1218','kota' => 'KABUPATEN SERDANG BEDAGAI'],
            ['id' => '1219','id_provinsi' => '12','kode_kota' => '1219','kota' => 'KABUPATEN BATU BARA'],
            ['id' => '1220','id_provinsi' => '12','kode_kota' => '1220','kota' => 'KABUPATEN PADANG LAWAS UTARA'],
            ['id' => '1221','id_provinsi' => '12','kode_kota' => '1221','kota' => 'KABUPATEN PADANG LAWAS'],
            ['id' => '1222','id_provinsi' => '12','kode_kota' => '1222','kota' => 'KABUPATEN LABUHAN BATU SELATAN'],
            ['id' => '1223','id_provinsi' => '12','kode_kota' => '1223','kota' => 'KABUPATEN LABUHAN BATU UTARA'],
            ['id' => '1224','id_provinsi' => '12','kode_kota' => '1224','kota' => 'KABUPATEN NIAS UTARA'],
            ['id' => '1225','id_provinsi' => '12','kode_kota' => '1225','kota' => 'KABUPATEN NIAS BARAT'],
            ['id' => '1271','id_provinsi' => '12','kode_kota' => '1271','kota' => 'KOTA SIBOLGA'],
            ['id' => '1272','id_provinsi' => '12','kode_kota' => '1272','kota' => 'KOTA TANJUNG BALAI'],
            ['id' => '1273','id_provinsi' => '12','kode_kota' => '1273','kota' => 'KOTA PEMATANG SIANTAR'],
            ['id' => '1274','id_provinsi' => '12','kode_kota' => '1274','kota' => 'KOTA TEBING TINGGI'],
            ['id' => '1275','id_provinsi' => '12','kode_kota' => '1275','kota' => 'KOTA MEDAN'],
            ['id' => '1276','id_provinsi' => '12','kode_kota' => '1276','kota' => 'KOTA BINJAI'],
            ['id' => '1277','id_provinsi' => '12','kode_kota' => '1277','kota' => 'KOTA PADANGSIDIMPUAN'],
            ['id' => '1278','id_provinsi' => '12','kode_kota' => '1278','kota' => 'KOTA GUNUNGSITOLI'],
            ['id' => '1301','id_provinsi' => '13','kode_kota' => '1301','kota' => 'KABUPATEN KEPULAUAN MENTAWAI'],
            ['id' => '1302','id_provinsi' => '13','kode_kota' => '1302','kota' => 'KABUPATEN PESISIR SELATAN'],
            ['id' => '1303','id_provinsi' => '13','kode_kota' => '1303','kota' => 'KABUPATEN SOLOK'],
            ['id' => '1304','id_provinsi' => '13','kode_kota' => '1304','kota' => 'KABUPATEN SIJUNJUNG'],
            ['id' => '1305','id_provinsi' => '13','kode_kota' => '1305','kota' => 'KABUPATEN TANAH DATAR'],
            ['id' => '1306','id_provinsi' => '13','kode_kota' => '1306','kota' => 'KABUPATEN PADANG PARIAMAN'],
            ['id' => '1307','id_provinsi' => '13','kode_kota' => '1307','kota' => 'KABUPATEN AGAM'],
            ['id' => '1308','id_provinsi' => '13','kode_kota' => '1308','kota' => 'KABUPATEN LIMA PULUH KOTA'],
            ['id' => '1309','id_provinsi' => '13','kode_kota' => '1309','kota' => 'KABUPATEN PASAMAN'],
            ['id' => '1310','id_provinsi' => '13','kode_kota' => '1310','kota' => 'KABUPATEN SOLOK SELATAN'],
            ['id' => '1311','id_provinsi' => '13','kode_kota' => '1311','kota' => 'KABUPATEN DHARMASRAYA'],
            ['id' => '1312','id_provinsi' => '13','kode_kota' => '1312','kota' => 'KABUPATEN PASAMAN BARAT'],
            ['id' => '1371','id_provinsi' => '13','kode_kota' => '1371','kota' => 'KOTA PADANG'],
            ['id' => '1372','id_provinsi' => '13','kode_kota' => '1372','kota' => 'KOTA SOLOK'],
            ['id' => '1373','id_provinsi' => '13','kode_kota' => '1373','kota' => 'KOTA SAWAH LUNTO'],
            ['id' => '1374','id_provinsi' => '13','kode_kota' => '1374','kota' => 'KOTA PADANG PANJANG'],
            ['id' => '1375','id_provinsi' => '13','kode_kota' => '1375','kota' => 'KOTA BUKITTINGGI'],
            ['id' => '1376','id_provinsi' => '13','kode_kota' => '1376','kota' => 'KOTA PAYAKUMBUH'],
            ['id' => '1377','id_provinsi' => '13','kode_kota' => '1377','kota' => 'KOTA PARIAMAN'],
            ['id' => '1401','id_provinsi' => '14','kode_kota' => '1401','kota' => 'KABUPATEN KUANTAN SINGINGI'],
            ['id' => '1402','id_provinsi' => '14','kode_kota' => '1402','kota' => 'KABUPATEN INDRAGIRI HULU'],
            ['id' => '1403','id_provinsi' => '14','kode_kota' => '1403','kota' => 'KABUPATEN INDRAGIRI HILIR'],
            ['id' => '1404','id_provinsi' => '14','kode_kota' => '1404','kota' => 'KABUPATEN PELALAWAN'],
            ['id' => '1405','id_provinsi' => '14','kode_kota' => '1405','kota' => 'KABUPATEN SIAK'],
            ['id' => '1406','id_provinsi' => '14','kode_kota' => '1406','kota' => 'KABUPATEN KAMPAR'],
            ['id' => '1407','id_provinsi' => '14','kode_kota' => '1407','kota' => 'KABUPATEN ROKAN HULU'],
            ['id' => '1408','id_provinsi' => '14','kode_kota' => '1408','kota' => 'KABUPATEN BENGKALIS'],
            ['id' => '1409','id_provinsi' => '14','kode_kota' => '1409','kota' => 'KABUPATEN ROKAN HILIR'],
            ['id' => '1410','id_provinsi' => '14','kode_kota' => '1410','kota' => 'KABUPATEN KEPULAUAN MERANTI'],
            ['id' => '1471','id_provinsi' => '14','kode_kota' => '1471','kota' => 'KOTA PEKANBARU'],
            ['id' => '1473','id_provinsi' => '14','kode_kota' => '1473','kota' => 'KOTA DUMAI'],
            ['id' => '1501','id_provinsi' => '15','kode_kota' => '1501','kota' => 'KABUPATEN KERINCI'],
            ['id' => '1502','id_provinsi' => '15','kode_kota' => '1502','kota' => 'KABUPATEN MERANGIN'],
            ['id' => '1503','id_provinsi' => '15','kode_kota' => '1503','kota' => 'KABUPATEN SAROLANGUN'],
            ['id' => '1504','id_provinsi' => '15','kode_kota' => '1504','kota' => 'KABUPATEN BATANG HARI'],
            ['id' => '1505','id_provinsi' => '15','kode_kota' => '1505','kota' => 'KABUPATEN MUARO JAMBI'],
            ['id' => '1506','id_provinsi' => '15','kode_kota' => '1506','kota' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
            ['id' => '1507','id_provinsi' => '15','kode_kota' => '1507','kota' => 'KABUPATEN TANJUNG JABUNG BARAT'],
            ['id' => '1508','id_provinsi' => '15','kode_kota' => '1508','kota' => 'KABUPATEN TEBO'],
            ['id' => '1509','id_provinsi' => '15','kode_kota' => '1509','kota' => 'KABUPATEN BUNGO'],
            ['id' => '1571','id_provinsi' => '15','kode_kota' => '1571','kota' => 'KOTA JAMBI'],
            ['id' => '1572','id_provinsi' => '15','kode_kota' => '1572','kota' => 'KOTA SUNGAI PENUH'],
            ['id' => '1601','id_provinsi' => '16','kode_kota' => '1601','kota' => 'KABUPATEN OGAN KOMERING ULU'],
            ['id' => '1602','id_provinsi' => '16','kode_kota' => '1602','kota' => 'KABUPATEN OGAN KOMERING ILIR'],
            ['id' => '1603','id_provinsi' => '16','kode_kota' => '1603','kota' => 'KABUPATEN MUARA ENIM'],
            ['id' => '1604','id_provinsi' => '16','kode_kota' => '1604','kota' => 'KABUPATEN LAHAT'],
            ['id' => '1605','id_provinsi' => '16','kode_kota' => '1605','kota' => 'KABUPATEN MUSI RAWAS'],
            ['id' => '1606','id_provinsi' => '16','kode_kota' => '1606','kota' => 'KABUPATEN MUSI BANYUASIN'],
            ['id' => '1607','id_provinsi' => '16','kode_kota' => '1607','kota' => 'KABUPATEN BANYU ASIN'],
            ['id' => '1608','id_provinsi' => '16','kode_kota' => '1608','kota' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
            ['id' => '1609','id_provinsi' => '16','kode_kota' => '1609','kota' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
            ['id' => '1610','id_provinsi' => '16','kode_kota' => '1610','kota' => 'KABUPATEN OGAN ILIR'],
            ['id' => '1611','id_provinsi' => '16','kode_kota' => '1611','kota' => 'KABUPATEN EMPAT LAWANG'],
            ['id' => '1612','id_provinsi' => '16','kode_kota' => '1612','kota' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
            ['id' => '1613','id_provinsi' => '16','kode_kota' => '1613','kota' => 'KABUPATEN MUSI RAWAS UTARA'],
            ['id' => '1671','id_provinsi' => '16','kode_kota' => '1671','kota' => 'KOTA PALEMBANG'],
            ['id' => '1672','id_provinsi' => '16','kode_kota' => '1672','kota' => 'KOTA PRABUMULIH'],
            ['id' => '1673','id_provinsi' => '16','kode_kota' => '1673','kota' => 'KOTA PAGAR ALAM'],
            ['id' => '1674','id_provinsi' => '16','kode_kota' => '1674','kota' => 'KOTA LUBUKLINGGAU'],
            ['id' => '1701','id_provinsi' => '17','kode_kota' => '1701','kota' => 'KABUPATEN BENGKULU SELATAN'],
            ['id' => '1702','id_provinsi' => '17','kode_kota' => '1702','kota' => 'KABUPATEN REJANG LEBONG'],
            ['id' => '1703','id_provinsi' => '17','kode_kota' => '1703','kota' => 'KABUPATEN BENGKULU UTARA'],
            ['id' => '1704','id_provinsi' => '17','kode_kota' => '1704','kota' => 'KABUPATEN KAUR'],
            ['id' => '1705','id_provinsi' => '17','kode_kota' => '1705','kota' => 'KABUPATEN SELUMA'],
            ['id' => '1706','id_provinsi' => '17','kode_kota' => '1706','kota' => 'KABUPATEN MUKOMUKO'],
            ['id' => '1707','id_provinsi' => '17','kode_kota' => '1707','kota' => 'KABUPATEN LEBONG'],
            ['id' => '1708','id_provinsi' => '17','kode_kota' => '1708','kota' => 'KABUPATEN KEPAHIANG'],
            ['id' => '1709','id_provinsi' => '17','kode_kota' => '1709','kota' => 'KABUPATEN BENGKULU TENGAH'],
            ['id' => '1771','id_provinsi' => '17','kode_kota' => '1771','kota' => 'KOTA BENGKULU'],
            ['id' => '1801','id_provinsi' => '18','kode_kota' => '1801','kota' => 'KABUPATEN LAMPUNG BARAT'],
            ['id' => '1802','id_provinsi' => '18','kode_kota' => '1802','kota' => 'KABUPATEN TANGGAMUS'],
            ['id' => '1803','id_provinsi' => '18','kode_kota' => '1803','kota' => 'KABUPATEN LAMPUNG SELATAN'],
            ['id' => '1804','id_provinsi' => '18','kode_kota' => '1804','kota' => 'KABUPATEN LAMPUNG TIMUR'],
            ['id' => '1805','id_provinsi' => '18','kode_kota' => '1805','kota' => 'KABUPATEN LAMPUNG TENGAH'],
            ['id' => '1806','id_provinsi' => '18','kode_kota' => '1806','kota' => 'KABUPATEN LAMPUNG UTARA'],
            ['id' => '1807','id_provinsi' => '18','kode_kota' => '1807','kota' => 'KABUPATEN WAY KANAN'],
            ['id' => '1808','id_provinsi' => '18','kode_kota' => '1808','kota' => 'KABUPATEN TULANGBAWANG'],
            ['id' => '1809','id_provinsi' => '18','kode_kota' => '1809','kota' => 'KABUPATEN PESAWARAN'],
            ['id' => '1810','id_provinsi' => '18','kode_kota' => '1810','kota' => 'KABUPATEN PRINGSEWU'],
            ['id' => '1811','id_provinsi' => '18','kode_kota' => '1811','kota' => 'KABUPATEN MESUJI'],
            ['id' => '1812','id_provinsi' => '18','kode_kota' => '1812','kota' => 'KABUPATEN TULANG BAWANG BARAT'],
            ['id' => '1813','id_provinsi' => '18','kode_kota' => '1813','kota' => 'KABUPATEN PESISIR BARAT'],
            ['id' => '1871','id_provinsi' => '18','kode_kota' => '1871','kota' => 'KOTA BANDAR LAMPUNG'],
            ['id' => '1872','id_provinsi' => '18','kode_kota' => '1872','kota' => 'KOTA METRO'],
            ['id' => '1901','id_provinsi' => '19','kode_kota' => '1901','kota' => 'KABUPATEN BANGKA'],
            ['id' => '1902','id_provinsi' => '19','kode_kota' => '1902','kota' => 'KABUPATEN BELITUNG'],
            ['id' => '1903','id_provinsi' => '19','kode_kota' => '1903','kota' => 'KABUPATEN BANGKA BARAT'],
            ['id' => '1904','id_provinsi' => '19','kode_kota' => '1904','kota' => 'KABUPATEN BANGKA TENGAH'],
            ['id' => '1905','id_provinsi' => '19','kode_kota' => '1905','kota' => 'KABUPATEN BANGKA SELATAN'],
            ['id' => '1906','id_provinsi' => '19','kode_kota' => '1906','kota' => 'KABUPATEN BELITUNG TIMUR'],
            ['id' => '1971','id_provinsi' => '19','kode_kota' => '1971','kota' => 'KOTA PANGKAL PINANG'],
            ['id' => '2101','id_provinsi' => '21','kode_kota' => '2101','kota' => 'KABUPATEN KARIMUN'],
            ['id' => '2102','id_provinsi' => '21','kode_kota' => '2102','kota' => 'KABUPATEN BINTAN'],
            ['id' => '2103','id_provinsi' => '21','kode_kota' => '2103','kota' => 'KABUPATEN NATUNA'],
            ['id' => '2104','id_provinsi' => '21','kode_kota' => '2104','kota' => 'KABUPATEN LINGGA'],
            ['id' => '2105','id_provinsi' => '21','kode_kota' => '2105','kota' => 'KABUPATEN KEPULAUAN ANAMBAS'],
            ['id' => '2171','id_provinsi' => '21','kode_kota' => '2171','kota' => 'KOTA BATAM'],
            ['id' => '2172','id_provinsi' => '21','kode_kota' => '2172','kota' => 'KOTA TANJUNG PINANG'],
            ['id' => '3101','id_provinsi' => '31','kode_kota' => '3101','kota' => 'KABUPATEN KEPULAUAN SERIBU'],
            ['id' => '3171','id_provinsi' => '31','kode_kota' => '3171','kota' => 'KOTA JAKARTA SELATAN'],
            ['id' => '3172','id_provinsi' => '31','kode_kota' => '3172','kota' => 'KOTA JAKARTA TIMUR'],
            ['id' => '3173','id_provinsi' => '31','kode_kota' => '3173','kota' => 'KOTA JAKARTA PUSAT'],
            ['id' => '3174','id_provinsi' => '31','kode_kota' => '3174','kota' => 'KOTA JAKARTA BARAT'],
            ['id' => '3175','id_provinsi' => '31','kode_kota' => '3175','kota' => 'KOTA JAKARTA UTARA'],
            ['id' => '3201','id_provinsi' => '32','kode_kota' => '3201','kota' => 'KABUPATEN BOGOR'],
            ['id' => '3202','id_provinsi' => '32','kode_kota' => '3202','kota' => 'KABUPATEN SUKABUMI'],
            ['id' => '3203','id_provinsi' => '32','kode_kota' => '3203','kota' => 'KABUPATEN CIANJUR'],
            ['id' => '3204','id_provinsi' => '32','kode_kota' => '3204','kota' => 'KABUPATEN BANDUNG'],
            ['id' => '3205','id_provinsi' => '32','kode_kota' => '3205','kota' => 'KABUPATEN GARUT'],
            ['id' => '3206','id_provinsi' => '32','kode_kota' => '3206','kota' => 'KABUPATEN TASIKMALAYA'],
            ['id' => '3207','id_provinsi' => '32','kode_kota' => '3207','kota' => 'KABUPATEN CIAMIS'],
            ['id' => '3208','id_provinsi' => '32','kode_kota' => '3208','kota' => 'KABUPATEN KUNINGAN'],
            ['id' => '3209','id_provinsi' => '32','kode_kota' => '3209','kota' => 'KABUPATEN CIREBON'],
            ['id' => '3210','id_provinsi' => '32','kode_kota' => '3210','kota' => 'KABUPATEN MAJALENGKA'],
            ['id' => '3211','id_provinsi' => '32','kode_kota' => '3211','kota' => 'KABUPATEN SUMEDANG'],
            ['id' => '3212','id_provinsi' => '32','kode_kota' => '3212','kota' => 'KABUPATEN INDRAMAYU'],
            ['id' => '3213','id_provinsi' => '32','kode_kota' => '3213','kota' => 'KABUPATEN SUBANG'],
            ['id' => '3214','id_provinsi' => '32','kode_kota' => '3214','kota' => 'KABUPATEN PURWAKARTA'],
            ['id' => '3215','id_provinsi' => '32','kode_kota' => '3215','kota' => 'KABUPATEN KARAWANG'],
            ['id' => '3216','id_provinsi' => '32','kode_kota' => '3216','kota' => 'KABUPATEN BEKASI'],
            ['id' => '3217','id_provinsi' => '32','kode_kota' => '3217','kota' => 'KABUPATEN BANDUNG BARAT'],
            ['id' => '3218','id_provinsi' => '32','kode_kota' => '3218','kota' => 'KABUPATEN PANGANDARAN'],
            ['id' => '3271','id_provinsi' => '32','kode_kota' => '3271','kota' => 'KOTA BOGOR'],
            ['id' => '3272','id_provinsi' => '32','kode_kota' => '3272','kota' => 'KOTA SUKABUMI'],
            ['id' => '3273','id_provinsi' => '32','kode_kota' => '3273','kota' => 'KOTA BANDUNG'],
            ['id' => '3274','id_provinsi' => '32','kode_kota' => '3274','kota' => 'KOTA CIREBON'],
            ['id' => '3275','id_provinsi' => '32','kode_kota' => '3275','kota' => 'KOTA BEKASI'],
            ['id' => '3276','id_provinsi' => '32','kode_kota' => '3276','kota' => 'KOTA DEPOK'],
            ['id' => '3277','id_provinsi' => '32','kode_kota' => '3277','kota' => 'KOTA CIMAHI'],
            ['id' => '3278','id_provinsi' => '32','kode_kota' => '3278','kota' => 'KOTA TASIKMALAYA'],
            ['id' => '3279','id_provinsi' => '32','kode_kota' => '3279','kota' => 'KOTA BANJAR'],
            ['id' => '3301','id_provinsi' => '33','kode_kota' => '3301','kota' => 'KABUPATEN CILACAP'],
            ['id' => '3302','id_provinsi' => '33','kode_kota' => '3302','kota' => 'KABUPATEN BANYUMAS'],
            ['id' => '3303','id_provinsi' => '33','kode_kota' => '3303','kota' => 'KABUPATEN PURBALINGGA'],
            ['id' => '3304','id_provinsi' => '33','kode_kota' => '3304','kota' => 'KABUPATEN BANJARNEGARA'],
            ['id' => '3305','id_provinsi' => '33','kode_kota' => '3305','kota' => 'KABUPATEN KEBUMEN'],
            ['id' => '3306','id_provinsi' => '33','kode_kota' => '3306','kota' => 'KABUPATEN PURWOREJO'],
            ['id' => '3307','id_provinsi' => '33','kode_kota' => '3307','kota' => 'KABUPATEN WONOSOBO'],
            ['id' => '3308','id_provinsi' => '33','kode_kota' => '3308','kota' => 'KABUPATEN MAGELANG'],
            ['id' => '3309','id_provinsi' => '33','kode_kota' => '3309','kota' => 'KABUPATEN BOYOLALI'],
            ['id' => '3310','id_provinsi' => '33','kode_kota' => '3310','kota' => 'KABUPATEN KLATEN'],
            ['id' => '3311','id_provinsi' => '33','kode_kota' => '3311','kota' => 'KABUPATEN SUKOHARJO'],
            ['id' => '3312','id_provinsi' => '33','kode_kota' => '3312','kota' => 'KABUPATEN WONOGIRI'],
            ['id' => '3313','id_provinsi' => '33','kode_kota' => '3313','kota' => 'KABUPATEN KARANGANYAR'],
            ['id' => '3314','id_provinsi' => '33','kode_kota' => '3314','kota' => 'KABUPATEN SRAGEN'],
            ['id' => '3315','id_provinsi' => '33','kode_kota' => '3315','kota' => 'KABUPATEN GROBOGAN'],
            ['id' => '3316','id_provinsi' => '33','kode_kota' => '3316','kota' => 'KABUPATEN BLORA'],
            ['id' => '3317','id_provinsi' => '33','kode_kota' => '3317','kota' => 'KABUPATEN REMBANG'],
            ['id' => '3318','id_provinsi' => '33','kode_kota' => '3318','kota' => 'KABUPATEN PATI'],
            ['id' => '3319','id_provinsi' => '33','kode_kota' => '3319','kota' => 'KABUPATEN KUDUS'],
            ['id' => '3320','id_provinsi' => '33','kode_kota' => '3320','kota' => 'KABUPATEN JEPARA'],
            ['id' => '3321','id_provinsi' => '33','kode_kota' => '3321','kota' => 'KABUPATEN DEMAK'],
            ['id' => '3322','id_provinsi' => '33','kode_kota' => '3322','kota' => 'KABUPATEN SEMARANG'],
            ['id' => '3323','id_provinsi' => '33','kode_kota' => '3323','kota' => 'KABUPATEN TEMANGGUNG'],
            ['id' => '3324','id_provinsi' => '33','kode_kota' => '3324','kota' => 'KABUPATEN KENDAL'],
            ['id' => '3325','id_provinsi' => '33','kode_kota' => '3325','kota' => 'KABUPATEN BATANG'],
            ['id' => '3326','id_provinsi' => '33','kode_kota' => '3326','kota' => 'KABUPATEN PEKALONGAN'],
            ['id' => '3327','id_provinsi' => '33','kode_kota' => '3327','kota' => 'KABUPATEN PEMALANG'],
            ['id' => '3328','id_provinsi' => '33','kode_kota' => '3328','kota' => 'KABUPATEN TEGAL'],
            ['id' => '3329','id_provinsi' => '33','kode_kota' => '3329','kota' => 'KABUPATEN BREBES'],
            ['id' => '3371','id_provinsi' => '33','kode_kota' => '3371','kota' => 'KOTA MAGELANG'],
            ['id' => '3372','id_provinsi' => '33','kode_kota' => '3372','kota' => 'KOTA SURAKARTA'],
            ['id' => '3373','id_provinsi' => '33','kode_kota' => '3373','kota' => 'KOTA SALATIGA'],
            ['id' => '3374','id_provinsi' => '33','kode_kota' => '3374','kota' => 'KOTA SEMARANG'],
            ['id' => '3375','id_provinsi' => '33','kode_kota' => '3375','kota' => 'KOTA PEKALONGAN'],
            ['id' => '3376','id_provinsi' => '33','kode_kota' => '3376','kota' => 'KOTA TEGAL'],
            ['id' => '3401','id_provinsi' => '34','kode_kota' => '3401','kota' => 'KABUPATEN KULON PROGO'],
            ['id' => '3402','id_provinsi' => '34','kode_kota' => '3402','kota' => 'KABUPATEN BANTUL'],
            ['id' => '3403','id_provinsi' => '34','kode_kota' => '3403','kota' => 'KABUPATEN GUNUNG KIDUL'],
            ['id' => '3404','id_provinsi' => '34','kode_kota' => '3404','kota' => 'KABUPATEN SLEMAN'],
            ['id' => '3471','id_provinsi' => '34','kode_kota' => '3471','kota' => 'KOTA YOGYAKARTA'],
            ['id' => '3501','id_provinsi' => '35','kode_kota' => '3501','kota' => 'KABUPATEN PACITAN'],
            ['id' => '3502','id_provinsi' => '35','kode_kota' => '3502','kota' => 'KABUPATEN PONOROGO'],
            ['id' => '3503','id_provinsi' => '35','kode_kota' => '3503','kota' => 'KABUPATEN TRENGGALEK'],
            ['id' => '3504','id_provinsi' => '35','kode_kota' => '3504','kota' => 'KABUPATEN TULUNGAGUNG'],
            ['id' => '3505','id_provinsi' => '35','kode_kota' => '3505','kota' => 'KABUPATEN BLITAR'],
            ['id' => '3506','id_provinsi' => '35','kode_kota' => '3506','kota' => 'KABUPATEN KEDIRI'],
            ['id' => '3507','id_provinsi' => '35','kode_kota' => '3507','kota' => 'KABUPATEN MALANG'],
            ['id' => '3508','id_provinsi' => '35','kode_kota' => '3508','kota' => 'KABUPATEN LUMAJANG'],
            ['id' => '3509','id_provinsi' => '35','kode_kota' => '3509','kota' => 'KABUPATEN JEMBER'],
            ['id' => '3510','id_provinsi' => '35','kode_kota' => '3510','kota' => 'KABUPATEN BANYUWANGI'],
            ['id' => '3511','id_provinsi' => '35','kode_kota' => '3511','kota' => 'KABUPATEN BONDOWOSO'],
            ['id' => '3512','id_provinsi' => '35','kode_kota' => '3512','kota' => 'KABUPATEN SITUBONDO'],
            ['id' => '3513','id_provinsi' => '35','kode_kota' => '3513','kota' => 'KABUPATEN PROBOLINGGO'],
            ['id' => '3514','id_provinsi' => '35','kode_kota' => '3514','kota' => 'KABUPATEN PASURUAN'],
            ['id' => '3515','id_provinsi' => '35','kode_kota' => '3515','kota' => 'KABUPATEN SIDOARJO'],
            ['id' => '3516','id_provinsi' => '35','kode_kota' => '3516','kota' => 'KABUPATEN MOJOKERTO'],
            ['id' => '3517','id_provinsi' => '35','kode_kota' => '3517','kota' => 'KABUPATEN JOMBANG'],
            ['id' => '3518','id_provinsi' => '35','kode_kota' => '3518','kota' => 'KABUPATEN NGANJUK'],
            ['id' => '3519','id_provinsi' => '35','kode_kota' => '3519','kota' => 'KABUPATEN MADIUN'],
            ['id' => '3520','id_provinsi' => '35','kode_kota' => '3520','kota' => 'KABUPATEN MAGETAN'],
            ['id' => '3521','id_provinsi' => '35','kode_kota' => '3521','kota' => 'KABUPATEN NGAWI'],
            ['id' => '3522','id_provinsi' => '35','kode_kota' => '3522','kota' => 'KABUPATEN BOJONEGORO'],
            ['id' => '3523','id_provinsi' => '35','kode_kota' => '3523','kota' => 'KABUPATEN TUBAN'],
            ['id' => '3524','id_provinsi' => '35','kode_kota' => '3524','kota' => 'KABUPATEN LAMONGAN'],
            ['id' => '3525','id_provinsi' => '35','kode_kota' => '3525','kota' => 'KABUPATEN GRESIK'],
            ['id' => '3526','id_provinsi' => '35','kode_kota' => '3526','kota' => 'KABUPATEN BANGKALAN'],
            ['id' => '3527','id_provinsi' => '35','kode_kota' => '3527','kota' => 'KABUPATEN SAMPANG'],
            ['id' => '3528','id_provinsi' => '35','kode_kota' => '3528','kota' => 'KABUPATEN PAMEKASAN'],
            ['id' => '3529','id_provinsi' => '35','kode_kota' => '3529','kota' => 'KABUPATEN SUMENEP'],
            ['id' => '3571','id_provinsi' => '35','kode_kota' => '3571','kota' => 'KOTA KEDIRI'],
            ['id' => '3572','id_provinsi' => '35','kode_kota' => '3572','kota' => 'KOTA BLITAR'],
            ['id' => '3573','id_provinsi' => '35','kode_kota' => '3573','kota' => 'KOTA MALANG'],
            ['id' => '3574','id_provinsi' => '35','kode_kota' => '3574','kota' => 'KOTA PROBOLINGGO'],
            ['id' => '3575','id_provinsi' => '35','kode_kota' => '3575','kota' => 'KOTA PASURUAN'],
            ['id' => '3576','id_provinsi' => '35','kode_kota' => '3576','kota' => 'KOTA MOJOKERTO'],
            ['id' => '3577','id_provinsi' => '35','kode_kota' => '3577','kota' => 'KOTA MADIUN'],
            ['id' => '3578','id_provinsi' => '35','kode_kota' => '3578','kota' => 'KOTA SURABAYA'],
            ['id' => '3579','id_provinsi' => '35','kode_kota' => '3579','kota' => 'KOTA BATU'],
            ['id' => '3601','id_provinsi' => '36','kode_kota' => '3601','kota' => 'KABUPATEN PANDEGLANG'],
            ['id' => '3602','id_provinsi' => '36','kode_kota' => '3602','kota' => 'KABUPATEN LEBAK'],
            ['id' => '3603','id_provinsi' => '36','kode_kota' => '3603','kota' => 'KABUPATEN TANGERANG'],
            ['id' => '3604','id_provinsi' => '36','kode_kota' => '3604','kota' => 'KABUPATEN SERANG'],
            ['id' => '3671','id_provinsi' => '36','kode_kota' => '3671','kota' => 'KOTA TANGERANG'],
            ['id' => '3672','id_provinsi' => '36','kode_kota' => '3672','kota' => 'KOTA CILEGON'],
            ['id' => '3673','id_provinsi' => '36','kode_kota' => '3673','kota' => 'KOTA SERANG'],
            ['id' => '3674','id_provinsi' => '36','kode_kota' => '3674','kota' => 'KOTA TANGERANG SELATAN'],
            ['id' => '5101','id_provinsi' => '51','kode_kota' => '5101','kota' => 'KABUPATEN JEMBRANA'],
            ['id' => '5102','id_provinsi' => '51','kode_kota' => '5102','kota' => 'KABUPATEN TABANAN'],
            ['id' => '5103','id_provinsi' => '51','kode_kota' => '5103','kota' => 'KABUPATEN BADUNG'],
            ['id' => '5104','id_provinsi' => '51','kode_kota' => '5104','kota' => 'KABUPATEN GIANYAR'],
            ['id' => '5105','id_provinsi' => '51','kode_kota' => '5105','kota' => 'KABUPATEN KLUNGKUNG'],
            ['id' => '5106','id_provinsi' => '51','kode_kota' => '5106','kota' => 'KABUPATEN BANGLI'],
            ['id' => '5107','id_provinsi' => '51','kode_kota' => '5107','kota' => 'KABUPATEN KARANG ASEM'],
            ['id' => '5108','id_provinsi' => '51','kode_kota' => '5108','kota' => 'KABUPATEN BULELENG'],
            ['id' => '5171','id_provinsi' => '51','kode_kota' => '5171','kota' => 'KOTA DENPASAR'],
            ['id' => '5201','id_provinsi' => '52','kode_kota' => '5201','kota' => 'KABUPATEN LOMBOK BARAT'],
            ['id' => '5202','id_provinsi' => '52','kode_kota' => '5202','kota' => 'KABUPATEN LOMBOK TENGAH'],
            ['id' => '5203','id_provinsi' => '52','kode_kota' => '5203','kota' => 'KABUPATEN LOMBOK TIMUR'],
            ['id' => '5204','id_provinsi' => '52','kode_kota' => '5204','kota' => 'KABUPATEN SUMBAWA'],
            ['id' => '5205','id_provinsi' => '52','kode_kota' => '5205','kota' => 'KABUPATEN DOMPU'],
            ['id' => '5206','id_provinsi' => '52','kode_kota' => '5206','kota' => 'KABUPATEN BIMA'],
            ['id' => '5207','id_provinsi' => '52','kode_kota' => '5207','kota' => 'KABUPATEN SUMBAWA BARAT'],
            ['id' => '5208','id_provinsi' => '52','kode_kota' => '5208','kota' => 'KABUPATEN LOMBOK UTARA'],
            ['id' => '5271','id_provinsi' => '52','kode_kota' => '5271','kota' => 'KOTA MATARAM'],
            ['id' => '5272','id_provinsi' => '52','kode_kota' => '5272','kota' => 'KOTA BIMA'],
            ['id' => '5301','id_provinsi' => '53','kode_kota' => '5301','kota' => 'KABUPATEN SUMBA BARAT'],
            ['id' => '5302','id_provinsi' => '53','kode_kota' => '5302','kota' => 'KABUPATEN SUMBA TIMUR'],
            ['id' => '5303','id_provinsi' => '53','kode_kota' => '5303','kota' => 'KABUPATEN KUPANG'],
            ['id' => '5304','id_provinsi' => '53','kode_kota' => '5304','kota' => 'KABUPATEN TIMOR TENGAH SELATAN'],
            ['id' => '5305','id_provinsi' => '53','kode_kota' => '5305','kota' => 'KABUPATEN TIMOR TENGAH UTARA'],
            ['id' => '5306','id_provinsi' => '53','kode_kota' => '5306','kota' => 'KABUPATEN BELU'],
            ['id' => '5307','id_provinsi' => '53','kode_kota' => '5307','kota' => 'KABUPATEN ALOR'],
            ['id' => '5308','id_provinsi' => '53','kode_kota' => '5308','kota' => 'KABUPATEN LEMBATA'],
            ['id' => '5309','id_provinsi' => '53','kode_kota' => '5309','kota' => 'KABUPATEN FLORES TIMUR'],
            ['id' => '5310','id_provinsi' => '53','kode_kota' => '5310','kota' => 'KABUPATEN SIKKA'],
            ['id' => '5311','id_provinsi' => '53','kode_kota' => '5311','kota' => 'KABUPATEN ENDE'],
            ['id' => '5312','id_provinsi' => '53','kode_kota' => '5312','kota' => 'KABUPATEN NGADA'],
            ['id' => '5313','id_provinsi' => '53','kode_kota' => '5313','kota' => 'KABUPATEN MANGGARAI'],
            ['id' => '5314','id_provinsi' => '53','kode_kota' => '5314','kota' => 'KABUPATEN ROTE NDAO'],
            ['id' => '5315','id_provinsi' => '53','kode_kota' => '5315','kota' => 'KABUPATEN MANGGARAI BARAT'],
            ['id' => '5316','id_provinsi' => '53','kode_kota' => '5316','kota' => 'KABUPATEN SUMBA TENGAH'],
            ['id' => '5317','id_provinsi' => '53','kode_kota' => '5317','kota' => 'KABUPATEN SUMBA BARAT DAYA'],
            ['id' => '5318','id_provinsi' => '53','kode_kota' => '5318','kota' => 'KABUPATEN NAGEKEO'],
            ['id' => '5319','id_provinsi' => '53','kode_kota' => '5319','kota' => 'KABUPATEN MANGGARAI TIMUR'],
            ['id' => '5320','id_provinsi' => '53','kode_kota' => '5320','kota' => 'KABUPATEN SABU RAIJUA'],
            ['id' => '5321','id_provinsi' => '53','kode_kota' => '5321','kota' => 'KABUPATEN MALAKA'],
            ['id' => '5371','id_provinsi' => '53','kode_kota' => '5371','kota' => 'KOTA KUPANG'],
            ['id' => '6101','id_provinsi' => '61','kode_kota' => '6101','kota' => 'KABUPATEN SAMBAS'],
            ['id' => '6102','id_provinsi' => '61','kode_kota' => '6102','kota' => 'KABUPATEN BENGKAYANG'],
            ['id' => '6103','id_provinsi' => '61','kode_kota' => '6103','kota' => 'KABUPATEN LANDAK'],
            ['id' => '6104','id_provinsi' => '61','kode_kota' => '6104','kota' => 'KABUPATEN MEMPAWAH'],
            ['id' => '6105','id_provinsi' => '61','kode_kota' => '6105','kota' => 'KABUPATEN SANGGAU'],
            ['id' => '6106','id_provinsi' => '61','kode_kota' => '6106','kota' => 'KABUPATEN KETAPANG'],
            ['id' => '6107','id_provinsi' => '61','kode_kota' => '6107','kota' => 'KABUPATEN SINTANG'],
            ['id' => '6108','id_provinsi' => '61','kode_kota' => '6108','kota' => 'KABUPATEN KAPUAS HULU'],
            ['id' => '6109','id_provinsi' => '61','kode_kota' => '6109','kota' => 'KABUPATEN SEKADAU'],
            ['id' => '6110','id_provinsi' => '61','kode_kota' => '6110','kota' => 'KABUPATEN MELAWI'],
            ['id' => '6111','id_provinsi' => '61','kode_kota' => '6111','kota' => 'KABUPATEN KAYONG UTARA'],
            ['id' => '6112','id_provinsi' => '61','kode_kota' => '6112','kota' => 'KABUPATEN KUBU RAYA'],
            ['id' => '6171','id_provinsi' => '61','kode_kota' => '6171','kota' => 'KOTA PONTIANAK'],
            ['id' => '6172','id_provinsi' => '61','kode_kota' => '6172','kota' => 'KOTA SINGKAWANG'],
            ['id' => '6201','id_provinsi' => '62','kode_kota' => '6201','kota' => 'KABUPATEN KOTAWARINGIN BARAT'],
            ['id' => '6202','id_provinsi' => '62','kode_kota' => '6202','kota' => 'KABUPATEN KOTAWARINGIN TIMUR'],
            ['id' => '6203','id_provinsi' => '62','kode_kota' => '6203','kota' => 'KABUPATEN KAPUAS'],
            ['id' => '6204','id_provinsi' => '62','kode_kota' => '6204','kota' => 'KABUPATEN BARITO SELATAN'],
            ['id' => '6205','id_provinsi' => '62','kode_kota' => '6205','kota' => 'KABUPATEN BARITO UTARA'],
            ['id' => '6206','id_provinsi' => '62','kode_kota' => '6206','kota' => 'KABUPATEN SUKAMARA'],
            ['id' => '6207','id_provinsi' => '62','kode_kota' => '6207','kota' => 'KABUPATEN LAMANDAU'],
            ['id' => '6208','id_provinsi' => '62','kode_kota' => '6208','kota' => 'KABUPATEN SERUYAN'],
            ['id' => '6209','id_provinsi' => '62','kode_kota' => '6209','kota' => 'KABUPATEN KATINGAN'],
            ['id' => '6210','id_provinsi' => '62','kode_kota' => '6210','kota' => 'KABUPATEN PULANG PISAU'],
            ['id' => '6211','id_provinsi' => '62','kode_kota' => '6211','kota' => 'KABUPATEN GUNUNG MAS'],
            ['id' => '6212','id_provinsi' => '62','kode_kota' => '6212','kota' => 'KABUPATEN BARITO TIMUR'],
            ['id' => '6213','id_provinsi' => '62','kode_kota' => '6213','kota' => 'KABUPATEN MURUNG RAYA'],
            ['id' => '6271','id_provinsi' => '62','kode_kota' => '6271','kota' => 'KOTA PALANGKA RAYA'],
            ['id' => '6301','id_provinsi' => '63','kode_kota' => '6301','kota' => 'KABUPATEN TANAH LAUT'],
            ['id' => '6302','id_provinsi' => '63','kode_kota' => '6302','kota' => 'KABUPATEN KOTA BARU'],
            ['id' => '6303','id_provinsi' => '63','kode_kota' => '6303','kota' => 'KABUPATEN BANJAR'],
            ['id' => '6304','id_provinsi' => '63','kode_kota' => '6304','kota' => 'KABUPATEN BARITO KUALA'],
            ['id' => '6305','id_provinsi' => '63','kode_kota' => '6305','kota' => 'KABUPATEN TAPIN'],
            ['id' => '6306','id_provinsi' => '63','kode_kota' => '6306','kota' => 'KABUPATEN HULU SUNGAI SELATAN'],
            ['id' => '6307','id_provinsi' => '63','kode_kota' => '6307','kota' => 'KABUPATEN HULU SUNGAI TENGAH'],
            ['id' => '6308','id_provinsi' => '63','kode_kota' => '6308','kota' => 'KABUPATEN HULU SUNGAI UTARA'],
            ['id' => '6309','id_provinsi' => '63','kode_kota' => '6309','kota' => 'KABUPATEN TABALONG'],
            ['id' => '6310','id_provinsi' => '63','kode_kota' => '6310','kota' => 'KABUPATEN TANAH BUMBU'],
            ['id' => '6311','id_provinsi' => '63','kode_kota' => '6311','kota' => 'KABUPATEN BALANGAN'],
            ['id' => '6371','id_provinsi' => '63','kode_kota' => '6371','kota' => 'KOTA BANJARMASIN'],
            ['id' => '6372','id_provinsi' => '63','kode_kota' => '6372','kota' => 'KOTA BANJAR BARU'],
            ['id' => '6401','id_provinsi' => '64','kode_kota' => '6401','kota' => 'KABUPATEN PASER'],
            ['id' => '6402','id_provinsi' => '64','kode_kota' => '6402','kota' => 'KABUPATEN KUTAI BARAT'],
            ['id' => '6403','id_provinsi' => '64','kode_kota' => '6403','kota' => 'KABUPATEN KUTAI KARTANEGARA'],
            ['id' => '6404','id_provinsi' => '64','kode_kota' => '6404','kota' => 'KABUPATEN KUTAI TIMUR'],
            ['id' => '6405','id_provinsi' => '64','kode_kota' => '6405','kota' => 'KABUPATEN BERAU'],
            ['id' => '6409','id_provinsi' => '64','kode_kota' => '6409','kota' => 'KABUPATEN PENAJAM PASER UTARA'],
            ['id' => '6411','id_provinsi' => '64','kode_kota' => '6411','kota' => 'KABUPATEN MAHAKAM HULU'],
            ['id' => '6471','id_provinsi' => '64','kode_kota' => '6471','kota' => 'KOTA BALIKPAPAN'],
            ['id' => '6472','id_provinsi' => '64','kode_kota' => '6472','kota' => 'KOTA SAMARINDA'],
            ['id' => '6474','id_provinsi' => '64','kode_kota' => '6474','kota' => 'KOTA BONTANG'],
            ['id' => '6501','id_provinsi' => '65','kode_kota' => '6501','kota' => 'KABUPATEN MALINAU'],
            ['id' => '6502','id_provinsi' => '65','kode_kota' => '6502','kota' => 'KABUPATEN BULUNGAN'],
            ['id' => '6503','id_provinsi' => '65','kode_kota' => '6503','kota' => 'KABUPATEN TANA TIDUNG'],
            ['id' => '6504','id_provinsi' => '65','kode_kota' => '6504','kota' => 'KABUPATEN NUNUKAN'],
            ['id' => '6571','id_provinsi' => '65','kode_kota' => '6571','kota' => 'KOTA TARAKAN'],
            ['id' => '7101','id_provinsi' => '71','kode_kota' => '7101','kota' => 'KABUPATEN BOLAANG MONGONDOW'],
            ['id' => '7102','id_provinsi' => '71','kode_kota' => '7102','kota' => 'KABUPATEN MINAHASA'],
            ['id' => '7103','id_provinsi' => '71','kode_kota' => '7103','kota' => 'KABUPATEN KEPULAUAN SANGIHE'],
            ['id' => '7104','id_provinsi' => '71','kode_kota' => '7104','kota' => 'KABUPATEN KEPULAUAN TALAUD'],
            ['id' => '7105','id_provinsi' => '71','kode_kota' => '7105','kota' => 'KABUPATEN MINAHASA SELATAN'],
            ['id' => '7106','id_provinsi' => '71','kode_kota' => '7106','kota' => 'KABUPATEN MINAHASA UTARA'],
            ['id' => '7107','id_provinsi' => '71','kode_kota' => '7107','kota' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
            ['id' => '7108','id_provinsi' => '71','kode_kota' => '7108','kota' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
            ['id' => '7109','id_provinsi' => '71','kode_kota' => '7109','kota' => 'KABUPATEN MINAHASA TENGGARA'],
            ['id' => '7110','id_provinsi' => '71','kode_kota' => '7110','kota' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
            ['id' => '7111','id_provinsi' => '71','kode_kota' => '7111','kota' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
            ['id' => '7171','id_provinsi' => '71','kode_kota' => '7171','kota' => 'KOTA MANADO'],
            ['id' => '7172','id_provinsi' => '71','kode_kota' => '7172','kota' => 'KOTA BITUNG'],
            ['id' => '7173','id_provinsi' => '71','kode_kota' => '7173','kota' => 'KOTA TOMOHON'],
            ['id' => '7174','id_provinsi' => '71','kode_kota' => '7174','kota' => 'KOTA KOTAMOBAGU'],
            ['id' => '7201','id_provinsi' => '72','kode_kota' => '7201','kota' => 'KABUPATEN BANGGAI KEPULAUAN'],
            ['id' => '7202','id_provinsi' => '72','kode_kota' => '7202','kota' => 'KABUPATEN BANGGAI'],
            ['id' => '7203','id_provinsi' => '72','kode_kota' => '7203','kota' => 'KABUPATEN MOROWALI'],
            ['id' => '7204','id_provinsi' => '72','kode_kota' => '7204','kota' => 'KABUPATEN POSO'],
            ['id' => '7205','id_provinsi' => '72','kode_kota' => '7205','kota' => 'KABUPATEN DONGGALA'],
            ['id' => '7206','id_provinsi' => '72','kode_kota' => '7206','kota' => 'KABUPATEN TOLI-TOLI'],
            ['id' => '7207','id_provinsi' => '72','kode_kota' => '7207','kota' => 'KABUPATEN BUOL'],
            ['id' => '7208','id_provinsi' => '72','kode_kota' => '7208','kota' => 'KABUPATEN PARIGI MOUTONG'],
            ['id' => '7209','id_provinsi' => '72','kode_kota' => '7209','kota' => 'KABUPATEN TOJO UNA-UNA'],
            ['id' => '7210','id_provinsi' => '72','kode_kota' => '7210','kota' => 'KABUPATEN SIGI'],
            ['id' => '7211','id_provinsi' => '72','kode_kota' => '7211','kota' => 'KABUPATEN BANGGAI LAUT'],
            ['id' => '7212','id_provinsi' => '72','kode_kota' => '7212','kota' => 'KABUPATEN MOROWALI UTARA'],
            ['id' => '7271','id_provinsi' => '72','kode_kota' => '7271','kota' => 'KOTA PALU'],
            ['id' => '7301','id_provinsi' => '73','kode_kota' => '7301','kota' => 'KABUPATEN KEPULAUAN SELAYAR'],
            ['id' => '7302','id_provinsi' => '73','kode_kota' => '7302','kota' => 'KABUPATEN BULUKUMBA'],
            ['id' => '7303','id_provinsi' => '73','kode_kota' => '7303','kota' => 'KABUPATEN BANTAENG'],
            ['id' => '7304','id_provinsi' => '73','kode_kota' => '7304','kota' => 'KABUPATEN JENEPONTO'],
            ['id' => '7305','id_provinsi' => '73','kode_kota' => '7305','kota' => 'KABUPATEN TAKALAR'],
            ['id' => '7306','id_provinsi' => '73','kode_kota' => '7306','kota' => 'KABUPATEN GOWA'],
            ['id' => '7307','id_provinsi' => '73','kode_kota' => '7307','kota' => 'KABUPATEN SINJAI'],
            ['id' => '7308','id_provinsi' => '73','kode_kota' => '7308','kota' => 'KABUPATEN MAROS'],
            ['id' => '7309','id_provinsi' => '73','kode_kota' => '7309','kota' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
            ['id' => '7310','id_provinsi' => '73','kode_kota' => '7310','kota' => 'KABUPATEN BARRU'],
            ['id' => '7311','id_provinsi' => '73','kode_kota' => '7311','kota' => 'KABUPATEN BONE'],
            ['id' => '7312','id_provinsi' => '73','kode_kota' => '7312','kota' => 'KABUPATEN SOPPENG'],
            ['id' => '7313','id_provinsi' => '73','kode_kota' => '7313','kota' => 'KABUPATEN WAJO'],
            ['id' => '7314','id_provinsi' => '73','kode_kota' => '7314','kota' => 'KABUPATEN SIDENRENG RAPPANG'],
            ['id' => '7315','id_provinsi' => '73','kode_kota' => '7315','kota' => 'KABUPATEN PINRANG'],
            ['id' => '7316','id_provinsi' => '73','kode_kota' => '7316','kota' => 'KABUPATEN ENREKANG'],
            ['id' => '7317','id_provinsi' => '73','kode_kota' => '7317','kota' => 'KABUPATEN LUWU'],
            ['id' => '7318','id_provinsi' => '73','kode_kota' => '7318','kota' => 'KABUPATEN TANA TORAJA'],
            ['id' => '7322','id_provinsi' => '73','kode_kota' => '7322','kota' => 'KABUPATEN LUWU UTARA'],
            ['id' => '7325','id_provinsi' => '73','kode_kota' => '7325','kota' => 'KABUPATEN LUWU TIMUR'],
            ['id' => '7326','id_provinsi' => '73','kode_kota' => '7326','kota' => 'KABUPATEN TORAJA UTARA'],
            ['id' => '7371','id_provinsi' => '73','kode_kota' => '7371','kota' => 'KOTA MAKASSAR'],
            ['id' => '7372','id_provinsi' => '73','kode_kota' => '7372','kota' => 'KOTA PAREPARE'],
            ['id' => '7373','id_provinsi' => '73','kode_kota' => '7373','kota' => 'KOTA PALOPO'],
            ['id' => '7401','id_provinsi' => '74','kode_kota' => '7401','kota' => 'KABUPATEN BUTON'],
            ['id' => '7402','id_provinsi' => '74','kode_kota' => '7402','kota' => 'KABUPATEN MUNA'],
            ['id' => '7403','id_provinsi' => '74','kode_kota' => '7403','kota' => 'KABUPATEN KONAWE'],
            ['id' => '7404','id_provinsi' => '74','kode_kota' => '7404','kota' => 'KABUPATEN KOLAKA'],
            ['id' => '7405','id_provinsi' => '74','kode_kota' => '7405','kota' => 'KABUPATEN KONAWE SELATAN'],
            ['id' => '7406','id_provinsi' => '74','kode_kota' => '7406','kota' => 'KABUPATEN BOMBANA'],
            ['id' => '7407','id_provinsi' => '74','kode_kota' => '7407','kota' => 'KABUPATEN WAKATOBI'],
            ['id' => '7408','id_provinsi' => '74','kode_kota' => '7408','kota' => 'KABUPATEN KOLAKA UTARA'],
            ['id' => '7409','id_provinsi' => '74','kode_kota' => '7409','kota' => 'KABUPATEN BUTON UTARA'],
            ['id' => '7410','id_provinsi' => '74','kode_kota' => '7410','kota' => 'KABUPATEN KONAWE UTARA'],
            ['id' => '7411','id_provinsi' => '74','kode_kota' => '7411','kota' => 'KABUPATEN KOLAKA TIMUR'],
            ['id' => '7412','id_provinsi' => '74','kode_kota' => '7412','kota' => 'KABUPATEN KONAWE KEPULAUAN'],
            ['id' => '7413','id_provinsi' => '74','kode_kota' => '7413','kota' => 'KABUPATEN MUNA BARAT'],
            ['id' => '7414','id_provinsi' => '74','kode_kota' => '7414','kota' => 'KABUPATEN BUTON TENGAH'],
            ['id' => '7415','id_provinsi' => '74','kode_kota' => '7415','kota' => 'KABUPATEN BUTON SELATAN'],
            ['id' => '7471','id_provinsi' => '74','kode_kota' => '7471','kota' => 'KOTA KENDARI'],
            ['id' => '7472','id_provinsi' => '74','kode_kota' => '7472','kota' => 'KOTA BAUBAU'],
            ['id' => '7501','id_provinsi' => '75','kode_kota' => '7501','kota' => 'KABUPATEN BOALEMO'],
            ['id' => '7502','id_provinsi' => '75','kode_kota' => '7502','kota' => 'KABUPATEN GORONTALO'],
            ['id' => '7503','id_provinsi' => '75','kode_kota' => '7503','kota' => 'KABUPATEN POHUWATO'],
            ['id' => '7504','id_provinsi' => '75','kode_kota' => '7504','kota' => 'KABUPATEN BONE BOLANGO'],
            ['id' => '7505','id_provinsi' => '75','kode_kota' => '7505','kota' => 'KABUPATEN GORONTALO UTARA'],
            ['id' => '7571','id_provinsi' => '75','kode_kota' => '7571','kota' => 'KOTA GORONTALO'],
            ['id' => '7601','id_provinsi' => '76','kode_kota' => '7601','kota' => 'KABUPATEN MAJENE'],
            ['id' => '7602','id_provinsi' => '76','kode_kota' => '7602','kota' => 'KABUPATEN POLEWALI MANDAR'],
            ['id' => '7603','id_provinsi' => '76','kode_kota' => '7603','kota' => 'KABUPATEN MAMASA'],
            ['id' => '7604','id_provinsi' => '76','kode_kota' => '7604','kota' => 'KABUPATEN MAMUJU'],
            ['id' => '7605','id_provinsi' => '76','kode_kota' => '7605','kota' => 'KABUPATEN MAMUJU UTARA'],
            ['id' => '7606','id_provinsi' => '76','kode_kota' => '7606','kota' => 'KABUPATEN MAMUJU TENGAH'],
            ['id' => '8101','id_provinsi' => '81','kode_kota' => '8101','kota' => 'KABUPATEN MALUKU TENGGARA BARAT'],
            ['id' => '8102','id_provinsi' => '81','kode_kota' => '8102','kota' => 'KABUPATEN MALUKU TENGGARA'],
            ['id' => '8103','id_provinsi' => '81','kode_kota' => '8103','kota' => 'KABUPATEN MALUKU TENGAH'],
            ['id' => '8104','id_provinsi' => '81','kode_kota' => '8104','kota' => 'KABUPATEN BURU'],
            ['id' => '8105','id_provinsi' => '81','kode_kota' => '8105','kota' => 'KABUPATEN KEPULAUAN ARU'],
            ['id' => '8106','id_provinsi' => '81','kode_kota' => '8106','kota' => 'KABUPATEN SERAM BAGIAN BARAT'],
            ['id' => '8107','id_provinsi' => '81','kode_kota' => '8107','kota' => 'KABUPATEN SERAM BAGIAN TIMUR'],
            ['id' => '8108','id_provinsi' => '81','kode_kota' => '8108','kota' => 'KABUPATEN MALUKU BARAT DAYA'],
            ['id' => '8109','id_provinsi' => '81','kode_kota' => '8109','kota' => 'KABUPATEN BURU SELATAN'],
            ['id' => '8171','id_provinsi' => '81','kode_kota' => '8171','kota' => 'KOTA AMBON'],
            ['id' => '8172','id_provinsi' => '81','kode_kota' => '8172','kota' => 'KOTA TUAL'],
            ['id' => '8201','id_provinsi' => '82','kode_kota' => '8201','kota' => 'KABUPATEN HALMAHERA BARAT'],
            ['id' => '8202','id_provinsi' => '82','kode_kota' => '8202','kota' => 'KABUPATEN HALMAHERA TENGAH'],
            ['id' => '8203','id_provinsi' => '82','kode_kota' => '8203','kota' => 'KABUPATEN KEPULAUAN SULA'],
            ['id' => '8204','id_provinsi' => '82','kode_kota' => '8204','kota' => 'KABUPATEN HALMAHERA SELATAN'],
            ['id' => '8205','id_provinsi' => '82','kode_kota' => '8205','kota' => 'KABUPATEN HALMAHERA UTARA'],
            ['id' => '8206','id_provinsi' => '82','kode_kota' => '8206','kota' => 'KABUPATEN HALMAHERA TIMUR'],
            ['id' => '8207','id_provinsi' => '82','kode_kota' => '8207','kota' => 'KABUPATEN PULAU MOROTAI'],
            ['id' => '8208','id_provinsi' => '82','kode_kota' => '8208','kota' => 'KABUPATEN PULAU TALIABU'],
            ['id' => '8271','id_provinsi' => '82','kode_kota' => '8271','kota' => 'KOTA TERNATE'],
            ['id' => '8272','id_provinsi' => '82','kode_kota' => '8272','kota' => 'KOTA TIDORE KEPULAUAN'],
            ['id' => '9101','id_provinsi' => '91','kode_kota' => '9101','kota' => 'KABUPATEN FAKFAK'],
            ['id' => '9102','id_provinsi' => '91','kode_kota' => '9102','kota' => 'KABUPATEN KAIMANA'],
            ['id' => '9103','id_provinsi' => '91','kode_kota' => '9103','kota' => 'KABUPATEN TELUK WONDAMA'],
            ['id' => '9104','id_provinsi' => '91','kode_kota' => '9104','kota' => 'KABUPATEN TELUK BINTUNI'],
            ['id' => '9105','id_provinsi' => '91','kode_kota' => '9105','kota' => 'KABUPATEN MANOKWARI'],
            ['id' => '9106','id_provinsi' => '91','kode_kota' => '9106','kota' => 'KABUPATEN SORONG SELATAN'],
            ['id' => '9107','id_provinsi' => '91','kode_kota' => '9107','kota' => 'KABUPATEN SORONG'],
            ['id' => '9108','id_provinsi' => '91','kode_kota' => '9108','kota' => 'KABUPATEN RAJA AMPAT'],
            ['id' => '9109','id_provinsi' => '91','kode_kota' => '9109','kota' => 'KABUPATEN TAMBRAUW'],
            ['id' => '9110','id_provinsi' => '91','kode_kota' => '9110','kota' => 'KABUPATEN MAYBRAT'],
            ['id' => '9111','id_provinsi' => '91','kode_kota' => '9111','kota' => 'KABUPATEN MANOKWARI SELATAN'],
            ['id' => '9112','id_provinsi' => '91','kode_kota' => '9112','kota' => 'KABUPATEN PEGUNUNGAN ARFAK'],
            ['id' => '9171','id_provinsi' => '91','kode_kota' => '9171','kota' => 'KOTA SORONG'],
            ['id' => '9401','id_provinsi' => '94','kode_kota' => '9401','kota' => 'KABUPATEN MERAUKE'],
            ['id' => '9402','id_provinsi' => '94','kode_kota' => '9402','kota' => 'KABUPATEN JAYAWIJAYA'],
            ['id' => '9403','id_provinsi' => '94','kode_kota' => '9403','kota' => 'KABUPATEN JAYAPURA'],
            ['id' => '9404','id_provinsi' => '94','kode_kota' => '9404','kota' => 'KABUPATEN NABIRE'],
            ['id' => '9408','id_provinsi' => '94','kode_kota' => '9408','kota' => 'KABUPATEN KEPULAUAN YAPEN'],
            ['id' => '9409','id_provinsi' => '94','kode_kota' => '9409','kota' => 'KABUPATEN BIAK NUMFOR'],
            ['id' => '9410','id_provinsi' => '94','kode_kota' => '9410','kota' => 'KABUPATEN PANIAI'],
            ['id' => '9411','id_provinsi' => '94','kode_kota' => '9411','kota' => 'KABUPATEN PUNCAK JAYA'],
            ['id' => '9412','id_provinsi' => '94','kode_kota' => '9412','kota' => 'KABUPATEN MIMIKA'],
            ['id' => '9413','id_provinsi' => '94','kode_kota' => '9413','kota' => 'KABUPATEN BOVEN DIGOEL'],
            ['id' => '9414','id_provinsi' => '94','kode_kota' => '9414','kota' => 'KABUPATEN MAPPI'],
            ['id' => '9415','id_provinsi' => '94','kode_kota' => '9415','kota' => 'KABUPATEN ASMAT'],
            ['id' => '9416','id_provinsi' => '94','kode_kota' => '9416','kota' => 'KABUPATEN YAHUKIMO'],
            ['id' => '9417','id_provinsi' => '94','kode_kota' => '9417','kota' => 'KABUPATEN PEGUNUNGAN BINTANG'],
            ['id' => '9418','id_provinsi' => '94','kode_kota' => '9418','kota' => 'KABUPATEN TOLIKARA'],
            ['id' => '9419','id_provinsi' => '94','kode_kota' => '9419','kota' => 'KABUPATEN SARMI'],
            ['id' => '9420','id_provinsi' => '94','kode_kota' => '9420','kota' => 'KABUPATEN KEEROM'],
            ['id' => '9426','id_provinsi' => '94','kode_kota' => '9426','kota' => 'KABUPATEN WAROPEN'],
            ['id' => '9427','id_provinsi' => '94','kode_kota' => '9427','kota' => 'KABUPATEN SUPIORI'],
            ['id' => '9428','id_provinsi' => '94','kode_kota' => '9428','kota' => 'KABUPATEN MAMBERAMO RAYA'],
            ['id' => '9429','id_provinsi' => '94','kode_kota' => '9429','kota' => 'KABUPATEN NDUGA'],
            ['id' => '9430','id_provinsi' => '94','kode_kota' => '9430','kota' => 'KABUPATEN LANNY JAYA'],
            ['id' => '9431','id_provinsi' => '94','kode_kota' => '9431','kota' => 'KABUPATEN MAMBERAMO TENGAH'],
            ['id' => '9432','id_provinsi' => '94','kode_kota' => '9432','kota' => 'KABUPATEN YALIMO'],
            ['id' => '9433','id_provinsi' => '94','kode_kota' => '9433','kota' => 'KABUPATEN PUNCAK'],
            ['id' => '9434','id_provinsi' => '94','kode_kota' => '9434','kota' => 'KABUPATEN DOGIYAI'],
            ['id' => '9435','id_provinsi' => '94','kode_kota' => '9435','kota' => 'KABUPATEN INTAN JAYA'],
            ['id' => '9436','id_provinsi' => '94','kode_kota' => '9436','kota' => 'KABUPATEN DEIYAI'],
            ['id' => '9471','id_provinsi' => '94','kode_kota' => '9471','kota' => 'KOTA JAYAPURA'],

            


            ]);			
		}
}